name: Deploy Next.js to Azure Web App - docvalidator-app

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build (Next.js standalone)
        run: npm run build
        # Requires next.config.js in repo and package.json start script uses PORT

      - name: Prepare deploy package (standalone output)
        run: |
          rm -rf package
          mkdir -p package
          cp -r .next/standalone/* package/
          mkdir -p package/.next/static
          cp -r .next/static package/.next/static
          if [ -d public ]; then cp -r public package/public; fi
          cp package.json package/package.json

      - name: Create zip artifact
        run: (cd package && zip -r ../app.zip .)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-zip
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-zip

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B49321364C594CF3BFA5775AAB543410 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E878D9CF0F644786B7E0358E2DBA2EC9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E40F12ECD2244322B9CA34F8F2215DCF }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: docvalidator-app
          slot-name: Production
          package: app.zip
