name: Deploy Next.js to Azure Web App - docvalidator-app

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build (Next.js standalone)
        run: npm run build
        # requires next.config.js with: output: 'standalone'

      - name: Prepare deploy package (include dotfiles)
        run: |
          rm -rf package
          mkdir -p package
          # Copy EVERYTHING from .next/standalone (including the hidden `.next` directory)
          rsync -a .next/standalone/ package/
          # Copy static assets used by Next
          mkdir -p package/.next/static
          rsync -a .next/static/ package/.next/static/
          # Public assets (if any)
          if [ -d public ]; then rsync -a public/ package/public/; fi
          # IMPORTANT: do NOT copy your root package.json here;
          # the standalone bundle already includes what it needs.
          # Azure will run `node server.js` because you set the Startup Command.

      - name: Create zip artifact
        run: (cd package && zip -r ../app.zip .)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-zip
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-zip

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B49321364C594CF3BFA5775AAB543410 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E878D9CF0F644786B7E0358E2DBA2EC9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E40F12ECD2244322B9CA34F8F2215DCF }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: docvalidator-app
          slot-name: Production
          package: app.zip
